export const FETCH_FITLERS_START = 'FETCH_FITLERS_START';
export const FETCH_FITLERS_SUCCESS = 'FETCH_FITLERS_SUCCESS';
export const FETCH_FITLERS_FAIL = 'FETCH_FITLERS_FAIL';
export const FETCH_HEADERS = 'FETCH_HEADERS';
export const FETCH_VALUES = 'FETCH_VALUES';
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const PUSH_LAST_SELECTED_VALUES = 'PUSH_LAST_SELECTED_VALUES';


export const APPEND_FILTER = 'APPEND_FILTER';
export const APPEND_FILTER_VALUE = 'APPEND_FILTER_VALUE';