export const FETCH_FITLERS_START = 'FETCH_FITLERS_START';
export const FETCH_FITLERS_SUCCESS = 'FETCH_FITLERS_SUCCESS';
export const FETCH_FITLERS_FAIL = 'FETCH_FITLERS_FAIL';

export const APPEND_FILTER = 'APPEND_FILTER';